### ISSUE TITLE
Modify NGINX configs

### ISSUE THREAD

**Issue by alexdwhite** [devmatics/cpetoday-issues#1]
Modify the NGINX configuration files in the reports.cpetoday.com website to match the CORS settings in reports.clockworksafety.com

- Server: aws-tools.cpetoday.com  (Tools/Web server)
- Site/Folder:  Reports (running MyDBR)
- Task:  Open up CORS so requests to https://reports.cpetoday.com won't be blocked

**Comment by WardenDrew** [comment]
CORS should be all set
![image](https://user-images.githubusercontent.com/32055840/141208250-0a2766f4-a86d-408c-982b-24eb1bb7e401.png)

Allowed origins regex: `^https?:\/\/(.*cpetoday\.com|localhost:(8080|8081|8082))$`

Should match cpetoday.com and any subdomains as well as localhost on ports 8080, 8081, and 8082

**Comment by alexdwhite** [comment]
Would you be able to double check this one?  It seems the main cpetoday.com website still has cors closed?

**Comment by WardenDrew** [comment]
CORS responses were only added to the reports.cpetoday.com site.
I'll add CORS responses to www.cpetoday.com and admin.cpetoday.com on the other AWS host once Steve gets me headers information
