### ISSUE TITLE
Bug - When I create a promotion code it throws an error when trying to make it active.

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/cpetoday-issues#4]
# Details
**Category:** Bug
**Short Description:** When I create a promotion code it throws an error when trying to make it active.
**Full Description:**
An error occurred while updating the entries. See the inner exception for details.

https://admin.cpetoday.com/Promotions/Enable?id=10
**Attachments:**
![](https://www.cpetoday.com/r/wp-content/uploads/formidable/3/chrome_6NTk4dJ7I3.png)
**Priority:** Medium
**User Type:** Staff
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.cpetoday.com/r//support-ticket/
**Submitted By:**
Steve Yoss (steve@devmatics.io)

# Related Issues

**Comment by alexdwhite** [comment]
Resolved with previous push
